AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ProcessKinesisRecords:
    Type: AWS::Serverless::Function
    Properties:
      Handler: putMetricToCloudwatch.handler
      Runtime: nodejs4.3
      Role: arn:aws:iam::431701745729:role/lambdaKinesisCloudwatch 
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt ExampleStream.Arn 
            BatchSize: 100
            StartingPosition: TRIM_HORIZON
  ExampleStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1