AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ExampleStream:
    Properties:
      ShardCount: 1
    Type: AWS::Kinesis::Stream
  ProcessKinesisRecords:
    Properties:
      CodeUri: s3://jiaoyang-lambda-demo/06b0e93bbc8d806392a0f3b15ab5c241
      Events:
        Stream:
          Properties:
            BatchSize: 100
            StartingPosition: TRIM_HORIZON
            Stream:
              Fn::GetAtt:
              - ExampleStream
              - Arn
          Type: Kinesis
      Handler: putMetricToCloudwatch.handler
      Role: arn:aws:iam::431701745729:role/lambdaKinesisCloudwatch
      Runtime: nodejs4.3
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
